### ISSUE TITLE
Checkbox field type not submitting data properly

### ISSUE THREAD

**Issue by kylenstone** [next-harm-reduction/encrypted-post#19]
Checkbox is not working correctly.  When the data is loaded in decrypt the submitted checkbox fields are omitted entirely.

Requirements:
* Any single checkbox passes validation
* Written text in `Other`passes validation

Console log from `test.html`
```
Uncaught (in promise) TypeError: Cannot read property 'aDataSort' of undefined
```

**Comment by kylenstone** [comment]
Note that 'required' is not working on fieldset as I had hoped it would.  We need a way to make a choice required for this field.  Since my validation is all HTML this could be done in JS but would be good to avoid that.

**Comment by schuyler1d** [comment]
I added a condition if there's a name attribute on the checkbox to send that.  the html will need to be updated.  Will need to investigate the 'multiselect' option.

**Comment by kylenstone** [comment]
Test notes:
* Basic use case works. Hooray!
* Multiselect works
* Selecting "other" and entering free form text does not work.  I've removed these fields from the form for the time being.
